typography_spectrum: 0.99512
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5707134518306702
  lightness: 0.6256020402070135
  saturation: 0.6582550180610269
  rhythmicContrast: 0.35660987882874906
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.25293
analytics:
  google: null
  facebook: null
  twitter: null
name: 'Michelle Stack '
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Wordpress
    url: 'https://michellestack.ca/'
    type: external
favicon: null
title: Michelle Stack
purpose: []
